In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder, OneHotEncoder
import pickle

In [3]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
data.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
#encoding
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
onehot_encoder_geo=OneHotEncoder()
geo_encoded=onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [7]:
geo_encoded.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [8]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [9]:
geo_encoded_df=pd.DataFrame(geo_encoded.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [10]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [11]:
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [13]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [14]:
#pickling the encoders and scalers
with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)
with open('scalar.pkl','wb') as file:
    pickle.dump(scaler,file)

## ANN

In [42]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [43]:
# Build the model
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)
])

#compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 64)                832

 dense_7 (Dense)             (None, 32)                2080

 dense_8 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [44]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

log_dir="regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [45]:
early_stopping=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [46]:
history=model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    #batch_size=32,
    callbacks=[early_stopping,tensorboard_callback]
    )

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 100378.2656 - mae: 100378.2656 - val_loss: 98520.8438 - val_mae: 98520.8438
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 99644.3125 - mae: 99644.3125 - val_loss: 97050.8594 - val_mae: 97050.8594
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 97082.3047 - mae: 97082.3047 - val_loss: 93306.8594 - val_mae: 93306.8594
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 92049.7031 - mae: 92049.7031 - val_loss: 87031.3281 - val_mae: 87031.3281
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 84701.7734 - mae: 84701.7734 - val_loss: 78862.1484 - val_mae: 78862.1484
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 75953.7812 - mae: 75953.7812 - val_loss: 70073.8594 - val_mae: 70073.8594
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 67287.0703 - mae: 67287.0703 - val_loss: 62367.8828 - val_mae: 62367.8828
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 60143.2031 - mae: 60143.2031 - val_loss: 56560.4375 - val_mae: 56560.4375
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 55331.2344 - mae: 55331.2344 - val_loss: 53103.1289 - val_mae: 53103.1289
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 52539.5859 - mae: 52539.5859 - val_loss: 51409.0078 - val_mae: 51409.0078
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 51218.4102 - mae: 51218.4102 - val_loss: 50861.0898 - val_mae: 50861.0898
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 50680.3750 - mae: 50680.3750 - val_loss: 50669.8438 - val_mae: 50669.8438
Epoch 13/100
250/250 [==============================] - 0s 1ms/step - loss: 50437.5078 - mae: 50437.5078 - val_loss: 50601.9531 - val_mae: 50601.9531
Epoch 14/100
250/250 [==============================] - 1s 2ms/step - loss: 50312.9648 - mae: 50312.9648 - val_loss: 50557.8906 - val_mae: 50557.8906
Epoch 15/100
250/250 [==============================] - 1s 2ms/step - loss: 50228.3359 - mae: 50228.3359 - val_loss: 50529.4805 - val_mae: 50529.4805
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 50165.8047 - mae: 50165.8047 - val_loss: 50507.5195 - val_mae: 50507.5195
Epoch 17/100
250/250 [==============================] - 0s 1ms/step - loss: 50116.2266 - mae: 50116.2266 - val_loss: 50487.9766 - val_mae: 50487.9766
Epoch 18/100
250/250 [==============================] - 0s 1ms/step - loss: 50073.6016 - mae: 50073.6016 - val_loss: 50470.1797 - val_mae: 50470.1797
Epoch 19/100
250/250 [==============================] - 0s 2ms/step - loss: 50031.1172 - mae: 50031.1172 - val_loss: 50460.7617 - val_mae: 50460.7617
Epoch 20/100
250/250 [==============================] - 0s 1ms/step - loss: 50000.2227 - mae: 50000.2227 - val_loss: 50445.0117 - val_mae: 50445.0117
Epoch 21/100
250/250 [==============================] - 0s 1ms/step - loss: 49970.0469 - mae: 49970.0469 - val_loss: 50435.8008 - val_mae: 50435.8008
Epoch 22/100
250/250 [==============================] - 0s 1ms/step - loss: 49943.1289 - mae: 49943.1289 - val_loss: 50417.2852 - val_mae: 50417.2852
Epoch 23/100
250/250 [==============================] - 0s 1ms/step - loss: 49919.2734 - mae: 49919.2734 - val_loss: 50408.8477 - val_mae: 50408.8477
Epoch 24/100
250/250 [==============================] - 0s 1ms/step - loss: 49893.2852 - mae: 49893.2852 - val_loss: 50391.5508 - val_mae: 50391.5508
Epoch 25/100
250/250 [==============================] - 0s 1ms/step - loss: 49871.4766 - mae: 49871.4766 - val_loss: 50380.8711 - val_mae: 50380.8711
Epoch 26/100
250/250 [==============================] - 0s 1ms/step - loss: 49852.1523 - mae: 49852.1523 - val_loss: 50376.2930 - val_mae: 50376.2930
Epoch 27/100
250/250 [==============================] - 0s 1ms/step - loss: 49830.0391 - mae: 49830.0391 - val_loss: 50355.9805 - val_mae: 50355.9805
Epoch 28/100
250/250 [==============================] - 0s 1ms/step - loss: 49810.8320 - mae: 49810.8320 - val_loss: 50348.8594 - val_mae: 50348.8594
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 49795.9062 - mae: 49795.9062 - val_loss: 50337.1016 - val_mae: 50337.1016
Epoch 30/100
250/250 [==============================] - 0s 2ms/step - loss: 49776.6055 - mae: 49776.6055 - val_loss: 50332.3242 - val_mae: 50332.3242
Epoch 31/100
250/250 [==============================] - 0s 1ms/step - loss: 49762.0078 - mae: 49762.0078 - val_loss: 50326.0625 - val_mae: 50326.0625
Epoch 32/100
250/250 [==============================] - 0s 2ms/step - loss: 49744.6133 - mae: 49744.6133 - val_loss: 50319.2266 - val_mae: 50319.2266
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 49732.5391 - mae: 49732.5391 - val_loss: 50309.2383 - val_mae: 50309.2383
Epoch 34/100
250/250 [==============================] - 0s 1ms/step - loss: 49718.3477 - mae: 49718.3477 - val_loss: 50308.6055 - val_mae: 50308.6055
Epoch 35/100
250/250 [==============================] - 0s 2ms/step - loss: 49704.0547 - mae: 49704.0547 - val_loss: 50300.9023 - val_mae: 50300.9023
Epoch 36/100
250/250 [==============================] - 0s 1ms/step - loss: 49693.5312 - mae: 49693.5312 - val_loss: 50300.9922 - val_mae: 50300.9922
Epoch 37/100
250/250 [==============================] - 0s 1ms/step - loss: 49683.7109 - mae: 49683.7109 - val_loss: 50296.5547 - val_mae: 50296.5547
Epoch 38/100
250/250 [==============================] - 0s 1ms/step - loss: 49670.0234 - mae: 49670.0234 - val_loss: 50290.6406 - val_mae: 50290.6406
Epoch 39/100
250/250 [==============================] - 0s 1ms/step - loss: 49660.4609 - mae: 49660.4609 - val_loss: 50292.7891 - val_mae: 50292.7891
Epoch 40/100
250/250 [==============================] - 0s 1ms/step - loss: 49649.6211 - mae: 49649.6211 - val_loss: 50293.3242 - val_mae: 50293.3242
Epoch 41/100
250/250 [==============================] - 0s 2ms/step - loss: 49641.6641 - mae: 49641.6641 - val_loss: 50283.0586 - val_mae: 50283.0586
Epoch 42/100
250/250 [==============================] - 0s 1ms/step - loss: 49632.8555 - mae: 49632.8555 - val_loss: 50282.4375 - val_mae: 50282.4375
Epoch 43/100
250/250 [==============================] - 0s 2ms/step - loss: 49621.6406 - mae: 49621.6406 - val_loss: 50291.8984 - val_mae: 50291.8984
Epoch 44/100
250/250 [==============================] - 0s 2ms/step - loss: 49615.3359 - mae: 49615.3359 - val_loss: 50287.5898 - val_mae: 50287.5898
Epoch 45/100
250/250 [==============================] - 0s 1ms/step - loss: 49606.4648 - mae: 49606.4648 - val_loss: 50284.6562 - val_mae: 50284.6562
Epoch 46/100
250/250 [==============================] - 0s 2ms/step - loss: 49599.2344 - mae: 49599.2344 - val_loss: 50279.5000 - val_mae: 50279.5000
Epoch 47/100
250/250 [==============================] - 0s 1ms/step - loss: 49587.0273 - mae: 49587.0273 - val_loss: 50287.2305 - val_mae: 50287.2305
Epoch 48/100
250/250 [==============================] - 0s 1ms/step - loss: 49579.2773 - mae: 49579.2773 - val_loss: 50284.5273 - val_mae: 50284.5273
Epoch 49/100
250/250 [==============================] - 0s 1ms/step - loss: 49572.1914 - mae: 49572.1914 - val_loss: 50284.9570 - val_mae: 50284.9570
Epoch 50/100
250/250 [==============================] - 0s 1ms/step - loss: 49566.0742 - mae: 49566.0742 - val_loss: 50285.3359 - val_mae: 50285.3359
Epoch 51/100
250/250 [==============================] - 0s 2ms/step - loss: 49556.7539 - mae: 49556.7539 - val_loss: 50275.0508 - val_mae: 50275.0508
Epoch 52/100
250/250 [==============================] - 0s 2ms/step - loss: 49552.0273 - mae: 49552.0273 - val_loss: 50279.9141 - val_mae: 50279.9141
Epoch 53/100
250/250 [==============================] - 0s 1ms/step - loss: 49546.9297 - mae: 49546.9297 - val_loss: 50280.1602 - val_mae: 50280.1602
Epoch 54/100
250/250 [==============================] - 0s 1ms/step - loss: 49542.5898 - mae: 49542.5898 - val_loss: 50298.7812 - val_mae: 50298.7812
Epoch 55/100
250/250 [==============================] - 0s 2ms/step - loss: 49536.9219 - mae: 49536.9219 - val_loss: 50290.9570 - val_mae: 50290.9570
Epoch 56/100
250/250 [==============================] - 0s 1ms/step - loss: 49526.3281 - mae: 49526.3281 - val_loss: 50285.2266 - val_mae: 50285.2266
Epoch 57/100
250/250 [==============================] - 0s 2ms/step - loss: 49520.6758 - mae: 49520.6758 - val_loss: 50294.3086 - val_mae: 50294.3086
Epoch 58/100
250/250 [==============================] - 0s 2ms/step - loss: 49513.6797 - mae: 49513.6797 - val_loss: 50278.8945 - val_mae: 50278.8945
Epoch 59/100
250/250 [==============================] - 0s 1ms/step - loss: 49509.1602 - mae: 49509.1602 - val_loss: 50281.7305 - val_mae: 50281.7305
Epoch 60/100
250/250 [==============================] - 0s 2ms/step - loss: 49510.9766 - mae: 49510.9766 - val_loss: 50292.1562 - val_mae: 50292.1562
Epoch 61/100
250/250 [==============================] - 0s 2ms/step - loss: 49500.1328 - mae: 49500.1328 - val_loss: 50296.4453 - val_mae: 50296.4453

In [49]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [50]:
%tensorboard --logdir=regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 52644), started 0:03:46 ago. (Use '!kill 52644' to kill it.)

In [51]:
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f"Test Loss: {test_loss}, Test MAE: {test_mae}")

63/63 [==============================] - 0s 1ms/step - loss: 50275.0508 - mae: 50275.0508
Test Loss: 50275.05078125, Test MAE: 50275.05078125

In [52]:
model.save('regression_model.h5')

c:\Users\praty\Downloads\ML\ChurnClassifier\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(